version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=todoapp
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"   # frontend accessible at http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
